AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  QueueName:
    Type: String
Resources:
  SpaQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: ${QueueName}
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "DeadLetterSpaQueue"
            - "Arn"
        maxReceiveCount: 5
  DeadLetterSpaQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName:
        Fn::Sub: ${QueueName}-dead
